// enums/role.enum.js

export const ROLES = {
  SUPER_ADMIN: "SuperAdmin",
  ORG_ADMIN: "OrgAdmin",
  MANAGER: "Manager",
  SUPPORT_AGENT: "SupportAgent",
  USER: "User",

  WORKSPACE_OWNER: "WorkspaceOwner",
  WORKSPACE_ADMIN: "WorkspaceAdmin",
  WORKSPACE_MEMBER: "WorkspaceMember",

  PROJECT_OWNER: "ProjectOwner",
  PROJECT_ADMIN: "ProjectAdmin",
  PROJECT_MEMBER: "ProjectMember",
  PROJECT_VIEWER: "ProjectViewer",
};

// 📦 Application Modules
export const MODULES = {
  USER: "user",
  ORGANIZATION: "organization",
  FIRM: "firm",
  LEAD: "lead",
  INVOICE: "invoice",
  CLIENT: "client",
  TAX: "tax",
  // Project Management (grouped)
  PROJECT: "project", // umbrella for workspace, project, task, member

  
};

export const PERMISSIONS = {
  // 👤 USER MODULE
  CREATE_USER: "CREATE_USER",
  VIEW_USER: "VIEW_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  SUSPEND_USER: "SUSPEND_USER",

  // 🏢 ORGANIZATION MODULE
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  VIEW_ORGANIZATION: "VIEW_ORGANIZATION",
  EDIT_ORGANIZATION: "EDIT_ORGANIZATION",
  DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
  SUSPEND_ORGANIZATION: "SUSPEND_ORGANIZATION",
  SEND_INVITATION: "SEND_INVITATION",
  DELETE_ORG_USER: "DELETE_ORG_USER",
  UPDATE_ORG_USER: "UPDATE_ORG_USER",
  VIEW_ORG_USER: "VIEW_ORG_USER",
  APPROVE_ORG_USER: "APPROVE_ORG_USER",

  // 🏛️ FIRM MODULE
  CREATE_FIRM: "CREATE_FIRM",
  VIEW_FIRM: "VIEW_FIRM",
  EDIT_FIRM: "EDIT_FIRM",
  DELETE_FIRM: "DELETE_FIRM",
  SUSPEND_FIRM: "SUSPEND_FIRM",
  RESTORE_FIRM: "RESTORE_FIRM",
  VIEW_TRASH: "VIEW_TRASH",

  // 🧾 INVOICE MODULE
  CREATE_INVOICE: "CREATE_INVOICE",
  VIEW_INVOICE: "VIEW_INVOICE",
  EDIT_INVOICE: "EDIT_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",
  EXPORT_INVOICE: "EXPORT_INVOICE",
  RESTORE_INVOICE: "RESTORE_INVOICE",

  // 👥 CLIENT MODULE
  CREATE_CLIENT: "CREATE_CLIENT",
  VIEW_CLIENT: "VIEW_CLIENT",
  EDIT_CLIENT: "EDIT_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",
  RESTORE_CLIENT: "RESTORE_CLIENT",

  // 📋 LEAD MODULE
  CREATE_LEAD: "CREATE_LEAD",
  VIEW_LEAD: "VIEW_LEAD",
  EDIT_LEAD: "EDIT_LEAD",
  DELETE_LEAD: "DELETE_LEAD",
  ASSIGN_LEAD: "ASSIGN_LEAD",
  RESTORE_LEAD: "RESTORE_LEAD",

  // 📊 TAX MODULE
  CREATE_TAX: "CREATE_TAX",
  VIEW_TAX: "VIEW_TAX",
  EDIT_TAX: "EDIT_TAX",
  DELETE_TAX: "DELETE_TAX",

  // 🔐 PERMISSION MODULE
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",

  // 🗂️ PROJECT MODULE (includes workspace/project/task/member)
  // Workspace
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  MANAGE_WORKSPACE_SETTINGS: "MANAGE_WORKSPACE_SETTINGS",
  TRANSFER_OWNERSHIP: "TRANSFER_OWNERSHIP",
  ARCHIVE_WORKSPACE: "ARCHIVE_WORKSPACE",
  VIEW_WORKSPACE_ANALYTICS: "VIEW_WORKSPACE_ANALYTICS",

  // Members
  ADD_MEMBER: "ADD_MEMBER",
  REMOVE_MEMBER: "REMOVE_MEMBER",
  CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",
  ASSIGN_MEMBER_TO_PROJECT: "ASSIGN_MEMBER_TO_PROJECT",
  INVITE_GUEST: "INVITE_GUEST",
  VIEW_MEMBER_LIST: "VIEW_MEMBER_LIST",

  // Projects
  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  ASSIGN_PROJECT_LEAD: "ASSIGN_PROJECT_LEAD",
  ARCHIVE_PROJECT: "ARCHIVE_PROJECT",
  VIEW_PROJECT_ACTIVITY: "VIEW_PROJECT_ACTIVITY",

  // Tasks
  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  ASSIGN_TASK: "ASSIGN_TASK",
  MARK_TASK_COMPLETE: "MARK_TASK_COMPLETE",
  COMMENT_ON_TASK: "COMMENT_ON_TASK",
  VIEW_TASK_HISTORY: "VIEW_TASK_HISTORY",

  // Extras
  EXPORT_DATA: "EXPORT_DATA",
  GENERATE_REPORT: "GENERATE_REPORT",
  INTEGRATE_THIRD_PARTY_APPS: "INTEGRATE_THIRD_PARTY_APPS",

  // View-only
  VIEW_ONLY: "VIEW_ONLY",
};
