// enums/role.enum.js

export const ROLES = {
  SUPER_ADMIN: "SuperAdmin",
  ORG_ADMIN: "OrgAdmin",
  MANAGER: "Manager",
  SUPPORT_AGENT: "SupportAgent",
  USER: "User",
  CUSTOM: "Custom",
};

export const MODULES = {
  USER: "user",
  ORGANIZATION: "organization",
  FIRM: "firm",
};

export const PERMISSIONS = {
  // USER MODULE
  CREATE_USER: "CREATE_USER",
  VIEW_USER: "VIEW_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",

  // ORGANIZATION MODULE
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  VIEW_ORGANIZATION: "VIEW_ORGANIZATION",
  EDIT_ORGANIZATION: "EDIT_ORGANIZATION",
  DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
  SEND_INVITATION: "SEND_INVITATION",
  DELETE_ORG_USER: "DELETE_ORG_USER",
  UPDATE_ORG_USER: "UPDATE_ORG_USER",
  VIEW_ORG_USER: "VIEW_ORG_USER",

  // FIRM MODULE
  CREATE_FIRM: "CREATE_FIRM",
  VIEW_FIRM: "VIEW_FIRM",
  EDIT_FIRM: "EDIT_FIRM",
  DELETE_FIRM: "DELETE_FIRM",
};
