// enums/role.enum.js

export const ROLES = {
  SUPER_ADMIN: "SuperAdmin",
  ORG_ADMIN: "OrgAdmin",
  MANAGER: "Manager",
  SUPPORT_AGENT: "SupportAgent",
  USER: "User",
  CUSTOM: "Custom",
};

// 📦 Application Modules
export const MODULES = {
  USER: "user",
  ORGANIZATION: "organization",
  FIRM: "firm",
  LEAD: "lead",
  INVOICE: "invoice",
  CLIENT: "client",
  TAX: "tax",

  
};

export const PERMISSIONS = {
  // USER MODULE
  CREATE_USER: "CREATE_USER",
  VIEW_USER: "VIEW_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  SUSPEND_USER: "SUSPEND_USER",
  // ORGANIZATION MODULE
  // 🏢 ORGANIZATION MODULE
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  VIEW_ORGANIZATION: "VIEW_ORGANIZATION",
  EDIT_ORGANIZATION: "EDIT_ORGANIZATION",
  DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
  SUSPEND_ORGANIZATION: "SUSPEND_ORGANIZATION",
  SEND_INVITATION: "SEND_INVITATION",
  DELETE_ORG_USER: "DELETE_ORG_USER",
  UPDATE_ORG_USER: "UPDATE_ORG_USER",
  VIEW_ORG_USER: "VIEW_ORG_USER",
  APPROVE_ORG_USER: "APPROVE_ORG_USER",

  // FIRM MODULE
  CREATE_FIRM: "CREATE_FIRM",
  VIEW_FIRM: "VIEW_FIRM",
  EDIT_FIRM: "EDIT_FIRM",
  DELETE_FIRM: "DELETE_FIRM",
  SUSPEND_FIRM: "SUSPEND_FIRM",
  RESTORE_FIRM: "RESTORE_FIRM",
  VIEW_TRASH: "VIEW_TRASH",
   // 🧾 INVOICE MODULE
  CREATE_INVOICE: "CREATE_INVOICE",
  VIEW_INVOICE: "VIEW_INVOICE",
  EDIT_INVOICE: "EDIT_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",
  EXPORT_INVOICE: "EXPORT_INVOICE",
   RESTORE_INVOICE: "RESTORE_INVOICE",
  VIEW_TRASH: "VIEW_TRASH",
// 🧑‍🤝‍🧑 CLIENT MODULE
  CREATE_CLIENT: "CREATE_CLIENT",
  VIEW_CLIENT: "VIEW_CLIENT",
  EDIT_CLIENT: "EDIT_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",
   RESTORE_CLIENT: "RESTORE_CLIENT",
  VIEW_TRASH: "VIEW_TRASH",
  // 📋 LEAD MODULE
  CREATE_LEAD: "CREATE_LEAD",
  VIEW_LEAD: "VIEW_LEAD",
  EDIT_LEAD: "EDIT_LEAD",
  DELETE_LEAD: "DELETE_LEAD",
  ASSIGN_LEAD: "ASSIGN_LEAD",
  RESTORE_LEAD: "RESTORE_LEAD",
  VIEW_TRASH: "VIEW_TRASH",
    // 📊 TAX MODULE
  CREATE_TAX: "CREATE_TAX",
  VIEW_TAX: "VIEW_TAX",
  EDIT_TAX: "EDIT_TAX",
  DELETE_TAX: "DELETE_TAX",
  // 🛡️ PERMISSION MODULE
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
};
